id = "demotape"
name = "Demo Tape"
description = "Syntax highlighting for Demo Tape terminal recording scripts"
version = "0.0.1"
schema_version = 1
authors = ["Nando Vieira <me@fnando.com>"]
repository = "https://github.com/fnando/zed-demotape"
snippets = "./snippets/demotape.json"

[grammars.demotape]
repository = "https://github.com/fnando/zed-demotape"
rev = "main"
path = "tree-sitter"
