---
name: Sync Zed Extension Code

on:
  workflow_dispatch:
    inputs: {}
  schedule:
    - cron: "0 * * * *" # Runs every hour

jobs:
  sync:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Checkout demotape
        uses: actions/checkout@v6
        with:
          repository: fnando/demotape
          path: demotape

      - name: Copy files
        run: |
          mkdir -p snippets
          cp -r demotape/editors/zed/* .
          cp demotape/editors/vscode/snippets/demotape.json snippets/demotape.json

      - name: Remove demotape directory
        run: rm -rf demotape

      - name: Commit and push changes
        run: |
          git config user.email "me@fnando.com"
          git config user.name "Nando Vieira via Github Actions"
          git add .
          if git diff --staged --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          git commit --message "Sync files."
          git pull origin --rebase
          git push origin
